spring.application.name=billing-service

#Setting the Port Number for Accepting the REST Request for Billing Service
server.port=4001
#Setting the Port Number for Accepting the gRPC Request for Billing Service
grpc.server.port=9001